image: registry.gitlab.com/interfaced/dev-server/base-ci-image:zb
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'develop'

before_script:
    - npm ci

lint:
    stage: test
    script:
    - npm run lint

test_tools:
    stage: test
    script:
    - npm run test.tools

test_framework:
    stage: test
    script:
    - npm run test.framework
